In [1]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression
import pickle

In [2]:
sizes = np.random.randint(500,35000,100)

In [3]:
sizes

array([ 2996,  4626,  5806, 29046, 29921,  3137,  7386, 11673, 26166,
        7200, 19404, 18593, 18254, 23319, 13457, 31909, 32115, 32139,
       13009, 27409, 25848, 26452, 26085, 25960, 18475, 14013, 16593,
       31009,  1560,  1907, 18144,  5066, 12659,  7241, 17916, 18637,
       32645, 28999, 22144,  5828, 28797,  7177,   622, 29043,  1926,
       33140, 32649, 25582,  2937, 20305, 34694, 21664, 30798, 11858,
       25254, 11485, 16658, 29619, 32920,  5020, 18625, 27649,  8399,
        2317, 27624, 24801, 16907, 22733, 32392,  1933, 18480,  7609,
       33889,  6803, 23989, 34383, 24272, 34165, 22206, 22184, 12073,
        4501, 17623, 12124,  3777, 20734, 25490, 33391, 28001, 25609,
       31363,  9184, 32393, 20145, 21607, 26041, 26714, 25433, 10455,
       34141])

In [4]:
bedrooms = np.random.randint(1,6,100)

In [5]:
len(bedrooms)

100

In [6]:
prices = (sizes*0.3)*(bedrooms*50)+np.random.randint(-200,200,100)

In [7]:
prices

array([ 134727.,   69304.,  261468.,  871345.,  897684.,   94272.,
        443280.,  525177., 1962405.,  432174.,  582225.,  836641.,
       1095157., 1049458.,  807356., 1914544., 1445007.,  964301.,
        585603.,  822205., 1550834., 1984020.,  391347., 1557782.,
        554066.,  630527.,  248915., 1860556.,   70147.,  143180.,
       1360702.,  228024.,  759469.,  542917.,  806136.,  838625.,
       1958685., 2174903.,  996317.,   87586.,  431953.,  323102.,
         27930., 1742671.,   86675., 2485410., 1958988., 1918603.,
        132099.,  304561., 2602061.,  974702.,  924045.,  177915.,
       1136357.,  689058.,  249943., 2221365.,  493825.,   75367.,
        279183.,  414580.,  503758.,   34770., 1243150., 1488007.,
        507161., 1364147., 1943385.,  116022., 1385962.,  114059.,
       2541644.,  408205., 1439531., 2578586., 1456455., 1537283.,
       1332432., 1663619.,  362275.,  270066., 1321854.,  363541.,
        169974., 1244085., 1911883., 2003377., 1680064., 15365

In [8]:
data = pd.DataFrame({'size_sqft':sizes,'bedrooms':bedrooms,'price':prices})

In [9]:
data.head()

size_sqft  bedrooms     price
0       2996         3  134727.0
1       4626         1   69304.0
2       5806         3  261468.0
3      29046         2  871345.0
4      29921         2  897684.0

In [10]:
X = data[ ["size_sqft","bedrooms"]]

In [11]:
y = data["price"]

In [12]:
model = LinearRegression()

In [13]:
model.fit(X,y)

LinearRegression()

In [14]:
sample_x = np.array([ [2000,3], [1500,2]])

In [15]:
model.predict(sample_x)

c:\Users\krish\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([  87489.4931835 , -240015.08283458])

In [16]:
with open("house_price_model.pkl","wb") as f:
    pickle.dump(model,f)